/**************************************************************
 * 核心词汇数据库 (根据上海英语中考大纲与常考重难点深度整理 - 豪华扩充版)
 **************************************************************/
const VOCABULARY_DB = [
    // --- 名词 (Noun) ---
    { word: "achievement", pos: "n.", meaning: "成就，成绩，功绩", category: "noun", example: "Winning the prize is a great achievement.", tip: "动词是achieve，注意名词拼写以-ment结尾" },
    { word: "broadcast", pos: "n. & v.", meaning: "广播，播送", category: "noun", example: "The live broadcast will begin at 8 p.m.", tip: "过去式和过去分词与原形一致" },
    { word: "communication", pos: "n.", meaning: "交流，沟通", category: "noun", example: "Language is a tool for communication.", tip: "动词是communicate，注意变名词去e加ion" },
    { word: "difficulty", pos: "n.", meaning: "困难，费劲", category: "noun", example: "We solved the problem with some difficulty.", tip: "形容词是difficult，不可数名词表抽象，可数名词表具体困难" },
    { word: "environment", pos: "n.", meaning: "环境", category: "noun", example: "Protecting the environment is our duty.", tip: "形容词是environmental，注意字母n容易漏掉" },
    { word: "education", pos: "n.", meaning: "教育，培养", category: "noun", example: "Education is important for everyone.", tip: "动词是educate，去e加ion" },
    { word: "information", pos: "n.", meaning: "信息，资料", category: "noun", example: "We can get information from the Internet.", tip: "不可数名词，没有复数形式，不能加s" },
    { word: "population", pos: "n.", meaning: "人口，人数", category: "noun", example: "The population of Shanghai is over 24 million.", tip: "常用单数，提问用what，形容人口多用large/big" },
    { word: "pronunciation", pos: "n.", meaning: "发音，读音", category: "noun", example: "Your pronunciation is very good.", tip: "动词是pronounce，注意名词拼写中没有o" },
    { word: "translation", pos: "n.", meaning: "翻译，译文", category: "noun", example: "The translation of this poem is beautiful.", tip: "动词是translate，-ion结尾" },
    { word: "situation", pos: "n.", meaning: "形势，情况，局面", category: "noun", example: "The situation is getting better.", tip: "注意拼写：s-i-t-u-a-t-i-o-n" },
    { word: "competition", pos: "n.", meaning: "比赛，竞赛", category: "noun", example: "She won the first prize in the competition.", tip: "动词是compete，注意双p，表示竞争对手是competitor" },
    { word: "celebration", pos: "n.", meaning: "庆祝，庆典", category: "noun", example: "We held a party in celebration of his birthday.", tip: "动词是celebrate，去e加ion" },
    { word: "description", pos: "n.", meaning: "描述，描写", category: "noun", example: "Can you give me a description of the thief?", tip: "动词是describe，注意describe变description时b变成p" },
    { word: "expression", pos: "n.", meaning: "表达，表情", category: "noun", example: "Reading aloud can improve your expression.", tip: "动词是express，加-ion变成名词" },
    { word: "discussion", pos: "n.", meaning: "讨论，议论", category: "noun", example: "We had a heated discussion about the plan.", tip: "动词是discuss，直接加-ion" },
    { word: "pollution", pos: "n.", meaning: "污染", category: "noun", example: "Air pollution is a serious problem.", tip: "动词是pollute，去e加ion" },
    { word: "attention", pos: "n.", meaning: "注意，关注", category: "noun", example: "Please pay attention to the teacher.", tip: "短语pay attention to，to是介词" },
    { word: "satisfaction", pos: "n.", meaning: "满意，满足", category: "noun", example: "He smiled with satisfaction.", tip: "形容词是satisfied/satisfactory，动词是satisfy" },
    { word: "imagination", pos: "n.", meaning: "想象力，创造力", category: "noun", example: "Children have rich imagination.", tip: "动词是imagine，去e加ation" },
    { word: "invitation", pos: "n.", meaning: "邀请，请柬", category: "noun", example: "Thank you for your invitation.", tip: "动词是invite，去e加ation" },
    { word: "preparation", pos: "n.", meaning: "准备，预备", category: "noun", example: "The preparation for the exam takes time.", tip: "动词是prepare，去e加ation，常与for搭配" },
    { word: "organization", pos: "n.", meaning: "组织，机构", category: "noun", example: "She works for a charity organization.", tip: "动词是organize，去e加ation" },
    { word: "honesty", pos: "n.", meaning: "诚实，老实", category: "noun", example: "Honesty is the best policy.", tip: "形容词是honest，h不发音" },
    { word: "knowledge", pos: "n.", meaning: "知识，学问", category: "noun", example: "Knowledge is power.", tip: "不可数名词，注意know和ledge两部分的结合" },
    { word: "decision", pos: "n.", meaning: "决定，抉择", category: "noun", example: "I have made a decision to study harder.", tip: "动词是decide，短语是make a decision" },
    { word: "pleasure", pos: "n.", meaning: "愉快，乐事", category: "noun", example: "It is a pleasure to meet you.", tip: "形容词是pleasant或pleased，It's a pleasure为常考交际用语" },
    { word: "success", pos: "n.", meaning: "成功", category: "noun", example: "Hard work leads to success.", tip: "动词是succeed，形容词是successful，注意双c双s" },
    { word: "invention", pos: "n.", meaning: "发明，创造", category: "noun", example: "The telephone was a great invention.", tip: "动词是invent，发明家是inventor" },
    { word: "activity", pos: "n.", meaning: "活动", category: "noun", example: "We take part in outdoor activities.", tip: "形容词是active，复数形式为activities" },
    // --- 新增上海中考高频名词 ---
    { word: "progress", pos: "n.", meaning: "进步，进展", category: "noun", example: "I have made great progress in English recently.", tip: "不可数名词！不能说a progress或progresses" },
    { word: "advice", pos: "n.", meaning: "建议，忠告", category: "noun", example: "Let me give you some useful advice.", tip: "不可数名词！表示一条建议用a piece of advice；动词是advise" },
    { word: "suggestion", pos: "n.", meaning: "建议，提议", category: "noun", example: "He made a good suggestion at the meeting.", tip: "可数名词！其动词是suggest" },
    { word: "experience", pos: "n.", meaning: "经验(不可数)；经历(可数)", category: "noun", example: "He has much work experience.", tip: "作为'经验'时不可数，作为'经历'时是可数名词" },
    { word: "ability", pos: "n.", meaning: "能力，本领", category: "noun", example: "She has the ability to speak three languages.", tip: "形容词是able，复数形式为abilities" },
    { word: "government", pos: "n.", meaning: "政府", category: "noun", example: "The government is building a new library.", tip: "动词是govern，注意中间的n不要漏写" },
    { word: "passenger", pos: "n.", meaning: "乘客，旅客", category: "noun", example: "The bus was full of passengers.", tip: "注意拼写：p-a-s-s-e-n-g-e-r" },
    { word: "influence", pos: "n. & v.", meaning: "影响，作用", category: "noun", example: "My parents have a great influence on me.", tip: "have an influence on... 对...有影响" },
    { word: "danger", pos: "n.", meaning: "危险", category: "noun", example: "The red light signs danger.", tip: "形容词是dangerous，in danger 处于危险中" },
    { word: "neighbour", pos: "n.", meaning: "邻居", category: "noun", example: "Our neighbours are very friendly.", tip: "注意拼写；美式为neighbor；邻里关系/社区是neighbourhood" },

    // --- 动词 (Verb) ---
    { word: "achieve", pos: "v.", meaning: "达到，取得，实现", category: "verb", example: "With efforts, you can achieve your goal.", tip: "名词是achievement，注意i在e前面" },
    { word: "communicate", pos: "v.", meaning: "交流，通讯", category: "verb", example: "We should communicate with each other often.", tip: "名词是communication，常用搭配：communicate with" },
    { word: "decide", pos: "v.", meaning: "决定，判决", category: "verb", example: "She decided to travel during the holiday.", tip: "名词是decision，常见搭配：decide to do sth." },
    { word: "succeed", pos: "v.", meaning: "成功，继承", category: "verb", example: "If you try hard, you will succeed.", tip: "名词是success，形容词是successful，succeed in doing sth." },
    { word: "encourage", pos: "v.", meaning: "鼓励，鼓舞", category: "verb", example: "My teacher encouraged me to speak English.", tip: "名词是encouragement，反义词是discourage，常用encourage sb. to do sth." },
    { word: "prepare", pos: "v.", meaning: "准备，筹备", category: "verb", example: "We are preparing for the exams.", tip: "名词是preparation，常见短语：prepare for sth. 或 prepare to do sth." },
    { word: "receive", pos: "v.", meaning: "收到，接待", category: "verb", example: "I received a letter from my friend.", tip: "注意c后面是ei，不是ie；强调收到这一客观事实，与accept(主观接受)区分" },
    { word: "recommend", pos: "v.", meaning: "推荐，介绍", category: "verb", example: "Can you recommend a good book to me?", tip: "名词是recommendation，注意是单c双m" },
    { word: "introduce", pos: "v.", meaning: "介绍，引进", category: "verb", example: "Let me introduce myself first.", tip: "名词是introduction，常见搭配：introduce sb. to sb." },
    { word: "disagree", pos: "v.", meaning: "不同意，反对", category: "verb", example: "I disagree with what you said.", tip: "反义词是agree，名词是disagreement，disagree with sb." },
    { word: "accept", pos: "v.", meaning: "接受，认可", category: "verb", example: "She accepted the job offer.", tip: "注意与except（除...之外）的区别，表示主观上接受" },
    { word: "afford", pos: "v.", meaning: "负担得起，抽得出", category: "verb", example: "I can't afford to buy that car.", tip: "常与can/can't连用，接动词不定式afford to do sth." },
    { word: "appear", pos: "v.", meaning: "出现，看起来", category: "verb", example: "He appeared to be very tired.", tip: "反义词是disappear，名词是appearance，作为系动词意为'显得/好像'" },
    { word: "compare", pos: "v.", meaning: "比较，对比", category: "verb", example: "Compare your answers with your partner's.", tip: "名词是comparison，短语compare...with... (把...和...比较)" },
    { word: "complete", pos: "v.", meaning: "完成，结束", category: "verb", example: "Please complete the form.", tip: "形容词也是complete，名词是completion，副词是completely" },
    { word: "consider", pos: "v.", meaning: "考虑，认为", category: "verb", example: "You should consider his suggestion.", tip: "consider doing sth. 考虑做某事；consider sb. as 认为某人是..." },
    { word: "depend", pos: "v.", meaning: "依靠，依赖", category: "verb", example: "It depends on the weather.", tip: "短语depend on/upon，形容词是dependent，名词是dependence" },
    { word: "describe", pos: "v.", meaning: "描述，描绘", category: "verb", example: "Can you describe what happened?", tip: "名词是description，常用于describe sb./sth. to sb." },
    { word: "develop", pos: "v.", meaning: "发展，开发，培养", category: "verb", example: "The city has developed rapidly.", tip: "名词是development，形容词是developed(发达的)/developing(发展中的)" },
    { word: "discover", pos: "v.", meaning: "发现，发觉", category: "verb", example: "Columbus discovered America in 1492.", tip: "名词是discovery，指发现原本就存在但未被认知的事物" },
    { word: "explain", pos: "v.", meaning: "解释，说明", category: "verb", example: "Please explain the meaning of this word.", tip: "名词是explanation，注意中间的i在名词中去掉了" },
    { word: "express", pos: "v.", meaning: "表达，表示", category: "verb", example: "She expressed her thanks to everyone.", tip: "名词是expression，express oneself表达自己的思想/感情" },
    { word: "improve", pos: "v.", meaning: "提高，改善", category: "verb", example: "I want to improve my English.", tip: "名词是improvement，指在原有基础上的提升" },
    { word: "include", pos: "v.", meaning: "包括，包含", category: "verb", example: "The price includes breakfast.", tip: "介词是including，常用于 A, including B 结构" },
    { word: "invite", pos: "v.", meaning: "邀请", category: "verb", example: "She invited me to her birthday party.", tip: "名词是invitation，invite sb. to do sth. 邀请某人做某事" },
    { word: "organize", pos: "v.", meaning: "组织，安排", category: "verb", example: "Let's organize a class meeting.", tip: "名词是organization，形容词是organized" },
    { word: "produce", pos: "v.", meaning: "生产，制造", category: "verb", example: "This factory produces cars.", tip: "名词是product(产品)/production(生产)" },
    { word: "protect", pos: "v.", meaning: "保护", category: "verb", example: "We should protect the environment.", tip: "名词是protection，常见搭配：protect...from/against... 保护...免受..." },
    { word: "provide", pos: "v.", meaning: "提供，供给", category: "verb", example: "The school provides us with textbooks.", tip: "短语provide sb. with sth. 或 provide sth. for sb." },
    { word: "reduce", pos: "v.", meaning: "减少，降低", category: "verb", example: "We should reduce the use of plastic bags.", tip: "名词是reduction，反义词是increase" },
    { word: "require", pos: "v.", meaning: "需要，要求", category: "verb", example: "This job requires patience.", tip: "名词是requirement，require sb. to do sth." },
    { word: "translate", pos: "v.", meaning: "翻译", category: "verb", example: "Can you translate this sentence into English?", tip: "名词是translation，翻译者是translator，translate...into..." },
    // --- 新增上海中考高频动词 ---
    { word: "suggest", pos: "v.", meaning: "建议，提议", category: "verb", example: "My teacher suggested practicing English every day.", tip: "上海中考超高频：suggest doing sth.！决不能接to do！名词是suggestion" },
    { word: "prefer", pos: "v.", meaning: "更喜欢", category: "verb", example: "I prefer reading books to watching TV.", tip: "过去式/过去分词双写r：preferred。prefer A to B (相比B更喜欢A，to是介词，后接doing)" },
    { word: "refuse", pos: "v.", meaning: "拒绝", category: "verb", example: "He refused to accept my invitation.", tip: "反义词是accept/agree，常见搭配：refuse to do sth. 拒绝做某事" },
    { word: "practice", pos: "v. & n.", meaning: "练习，实践", category: "verb", example: "You must practice playing the violin.", tip: "上海中考最爱考：practice doing sth.！名词和动词同形（英式名词写作practise）" },
    { word: "avoid", pos: "v.", meaning: "避免，躲避", category: "verb", example: "We should try to avoid making the same mistake.", tip: "上海中考必背：avoid doing sth. 避免做某事" },
    { word: "manage", pos: "v.", meaning: "设法做到；管理", category: "verb", example: "How did you manage to finish it so quickly?", tip: "manage to do sth. 设法成功做成某事，名词是manager(经理)" },
    { word: "realize", pos: "v.", meaning: "实现(梦想)；意识到", category: "verb", example: "I hope to realize my dream in the future.", tip: "常见搭配：realize one's dream，注意与come true(不及物，主语是物)辨析" },
    { word: "graduate", pos: "v. & n.", meaning: "毕业；毕业生", category: "verb", example: "She graduated from Fudan University.", tip: "graduate from... 从...毕业，名词形式是graduation" },

    // --- 形容词与副词 (Adjective & Adverb) ---
    { word: "beautifully", pos: "adv.", meaning: "美妙地，漂亮地", category: "adj_adv", example: "She sings beautifully.", tip: "形容词是beautiful，名词是beauty" },
    { word: "fluently", pos: "adv.", meaning: "流利地", category: "adj_adv", example: "He can speak English very fluently.", tip: "形容词是fluent，名词是fluency" },
    { word: "generous", pos: "adj.", meaning: "大方的，慷慨的", category: "adj_adv", example: "It's generous of you to buy me lunch.", tip: "名词是generosity，常用句型：It is generous of sb. to do sth." },
    { word: "honest", pos: "adj.", meaning: "诚实的，正直的", category: "adj_adv", example: "He is an honest boy.", tip: "注意前面的冠词用an，因为h不发音！名词是honesty，反义词是dishonest" },
    { word: "impossible", pos: "adj.", meaning: "不可能的", category: "adj_adv", example: "Nothing is impossible.", tip: "反义词是possible，前缀im-表示否定，副词是impossible -> impossibly" },
    { word: "patient", pos: "adj. & n.", meaning: "有耐心的；病人", category: "adj_adv", example: "Teachers should be patient with children.", tip: "名词是patience，反义词是impatient，be patient with sb." },
    { word: "successful", pos: "adj.", meaning: "成功的", category: "adj_adv", example: "He is a successful businessman.", tip: "副词是successfully，动词是succeed，名词是success" },
    { word: "unusual", pos: "adj.", meaning: "不寻常的，独特的", category: "adj_adv", example: "It is an unusual experience.", tip: "反义词是usual，前缀un-表示否定，副词是unusually" },
    { word: "different", pos: "adj.", meaning: "不同的", category: "adj_adv", example: "He has a different opinion.", tip: "名词是difference，副词是differently，be different from..." },
    { word: "safe", pos: "adj.", meaning: "安全的", category: "adj_adv", example: "Have a safe journey!", tip: "名词是safety，副词是safely，动词是save" },
    { word: "comfortable", pos: "adj.", meaning: "舒适的，舒服的", category: "adj_adv", example: "This sofa is very comfortable.", tip: "动词/名词是comfort，反义词uncomfortable" },
    { word: "convenient", pos: "adj.", meaning: "方便的，便利的", category: "adj_adv", example: "It's convenient to take the subway.", tip: "名词是convenience，反义词inconvenient，常用于 It's convenient for sb. to do sth." },
    { word: "dangerous", pos: "adj.", meaning: "危险的", category: "adj_adv", example: "It's dangerous to swim alone.", tip: "名词是danger，注意-ous是形容词后缀" },
    { word: "famous", pos: "adj.", meaning: "著名的，出名的", category: "adj_adv", example: "Shanghai is famous for the Bund.", tip: "短语be famous for(因...著名)/as(作为...而闻名)" },
    { word: "international", pos: "adj.", meaning: "国际的", category: "adj_adv", example: "English is an international language.", tip: "词根是nation，inter-表示'之间'" },
    { word: "necessary", pos: "adj.", meaning: "必要的，必需的", category: "adj_adv", example: "It is necessary to practice every day.", tip: "反义词是unnecessary，注意双写s，副词是necessarily" },
    { word: "pleasant", pos: "adj.", meaning: "令人愉快的", category: "adj_adv", example: "We had a pleasant journey.", tip: "动词是please，名词是pleasure，反义词unpleasant" },
    { word: "polite", pos: "adj.", meaning: "有礼貌的", category: "adj_adv", example: "You should be polite to your elders.", tip: "副词是politely，名词是politeness，反义词impolite" },
    { word: "popular", pos: "adj.", meaning: "流行的，受欢迎的", category: "adj_adv", example: "This song is very popular.", tip: "名词是popularity，短语be popular with sb." },
    { word: "proper", pos: "adj.", meaning: "恰当的，合适的", category: "adj_adv", example: "Fill in the blanks with proper words.", tip: "副词是properly，近义词是suitable" },
    { word: "responsible", pos: "adj.", meaning: "负责的，有责任心的", category: "adj_adv", example: "Parents are responsible for their children.", tip: "名词是responsibility，短语be responsible for" },
    { word: "serious", pos: "adj.", meaning: "严重的，认真的", category: "adj_adv", example: "Pollution is a serious problem.", tip: "副词是seriously，take...seriously认真对待" },
    { word: "traditional", pos: "adj.", meaning: "传统的", category: "adj_adv", example: "We eat mooncakes at the traditional festival.", tip: "名词是tradition，-al形容词后缀" },
    { word: "valuable", pos: "adj.", meaning: "有价值的，宝贵的", category: "adj_adv", example: "This is a valuable experience.", tip: "名词是value，同义词是precious" },
    { word: "wonderful", pos: "adj.", meaning: "精彩的，绝妙的", category: "adj_adv", example: "What a wonderful performance!", tip: "名词/动词是wonder，-ful形容词后缀" },
    // --- 新增上海中考高频形容词与副词 ---
    { word: "lively", pos: "adj.", meaning: "生动的，活泼的", category: "adj_adv", example: "The teacher made the class very lively.", tip: "虽然以-ly结尾，但是形容词！不是副词！" },
    { word: "asleep", pos: "adj.", meaning: "睡着的，熟睡的", category: "adj_adv", example: "The baby was fast asleep.", tip: "表语形容词，只能作表语，不能作定语！fall asleep(入睡)" },
    { word: "healthy", pos: "adj.", meaning: "健康的", category: "adj_adv", example: "Eating vegetables keeps you healthy.", tip: "名词是health，反义词是unhealthy，副词是healthily" },
    { word: "wealthy", pos: "adj.", meaning: "富有的，富裕的", category: "adj_adv", example: "He is a wealthy businessman.", tip: "名词是wealth(财富)，财富不可数，wealthy相当于rich" },
    { word: "blind", pos: "adj.", meaning: "瞎的，盲的", category: "adj_adv", example: "We should help blind people cross the street.", tip: "上海中考爱考残疾人文类关怀词，如deaf(聋的), mute(哑的)" },
    { word: "creative", pos: "adj.", meaning: "有创造力的", category: "adj_adv", example: "This is a highly creative design.", tip: "动词是create，名词是creation/creativity" },

    // --- 高频中考短语 (Phrases) ---
    { word: "depend on", pos: "phr.", meaning: "依靠，依赖，取决于", category: "phrase", example: "Children should not depend on parents too much.", tip: "等于rely on，d-e-p-e-n-d o-n" },
    { word: "instead of", pos: "phr.", meaning: "代替，而不是", category: "phrase", example: "We played soccer instead of watching TV.", tip: "of是介词，后面要加名词、代词或动名词(doing)" },
    { word: "look forward to", pos: "phr.", meaning: "期待，盼望", category: "phrase", example: "I look forward to hearing from you.", tip: "上海中考超高频考点！to是介词，后面必须跟名词、代词或doing" },
    { word: "take pride in", pos: "phr.", meaning: "为...感到自豪", category: "phrase", example: "The parents take pride in their son's success.", tip: "pride是名词，同义短语是be proud of" },
    { word: "be proud of", pos: "phr.", meaning: "为...感到骄傲/自豪", category: "phrase", example: "We are all proud of our great motherland.", tip: "proud是形容词，同义短语是take pride in" },
    { word: "pay attention to", pos: "phr.", meaning: "注意，留心", category: "phrase", example: "Please pay attention to your spelling.", tip: "to是介词，后面接名词、代词或动名词" },
    { word: "run out of", pos: "phr.", meaning: "用完，耗尽", category: "phrase", example: "We have run out of gas.", tip: "主语通常是人，主动语态。如果是物作主语，用run out" },
    { word: "agree with", pos: "phr.", meaning: "同意某人的意见", category: "phrase", example: "I agree with you in some ways.", tip: "后通常接人(sb.)，如果要接建议/决定，常用agree to (a plan/decision)" },
    { word: "give up", pos: "phr.", meaning: "放弃", category: "phrase", example: "Never give up easily.", tip: "give up doing sth. 表示放弃做某事，如果是代词放中间，如give it up" },
    { word: "make a decision", pos: "phr.", meaning: "做决定", category: "phrase", example: "It is hard to make a decision quickly.", tip: "等同于动词decide" },
    { word: "as soon as", pos: "phr.", meaning: "一...就...", category: "phrase", example: "I will call you as soon as I arrive.", tip: "引导时间状语从句，主句用将来时，从句用一般现在时（主将从现）" },
    { word: "at least", pos: "phr.", meaning: "至少", category: "phrase", example: "You should brush your teeth at least twice a day.", tip: "反义短语是at most（至多）" },
    { word: "be afraid of", pos: "phr.", meaning: "害怕...", category: "phrase", example: "Don't be afraid of making mistakes.", tip: "afraid是形容词，be afraid of doing sth. / be afraid to do sth." },
    { word: "be famous for", pos: "phr.", meaning: "因...而著名", category: "phrase", example: "Hangzhou is famous for the West Lake.", tip: "for后接原因/特色，as后接身份/职业" },
    { word: "be good at", pos: "phr.", meaning: "擅长...", category: "phrase", example: "She is good at playing the piano.", tip: "同义短语是do well in，反义是be weak in" },
    { word: "be interested in", pos: "phr.", meaning: "对...感兴趣", category: "phrase", example: "I am interested in science.", tip: "形容词interested(修饰人，表人感到...) / interesting(修饰物，表物令人...)" },
    { word: "be used to", pos: "phr.", meaning: "习惯于...", category: "phrase", example: "He is used to getting up early.", tip: "上海中考大核心：to是介词，后跟doing。注意与used to do（过去常常做，后接动词原形）区分" },
    { word: "by the way", pos: "phr.", meaning: "顺便说一下", category: "phrase", example: "By the way, what's your phone number?", tip: "用于转换话题或补充信息" },
    { word: "come true", pos: "phr.", meaning: "实现，成真", category: "phrase", example: "I hope my dream will come true.", tip: "不及物短语，不能接宾语，无被动语态，主语通常是dream/hope" },
    { word: "deal with", pos: "phr.", meaning: "处理，对付", category: "phrase", example: "How do you deal with the problem?", tip: "常与how连用。同义词为do with(常与what连用，如 What did you do with...)" },
    { word: "get along with", pos: "phr.", meaning: "与...相处", category: "phrase", example: "I get along well with my classmates.", tip: "也可用get on with，表示相处融洽" },
    { word: "grow up", pos: "phr.", meaning: "长大，成长", category: "phrase", example: "What do you want to be when you grow up?", tip: "过去式为grew up，过去分词为grown up" },
    { word: "hold on", pos: "phr.", meaning: "等一下；坚持", category: "phrase", example: "Hold on, please. Let me check.", tip: "打电话常用语(请稍等)，同义词hang on" },
    { word: "lead to", pos: "phr.", meaning: "导致，通向", category: "phrase", example: "Hard work leads to success.", tip: "lead-led-led，to是介词，后面接名词、代词或doing" },
    { word: "look after", pos: "phr.", meaning: "照顾，照看", category: "phrase", example: "Please look after your little sister.", tip: "同义短语是take care of" },
    { word: "make sure", pos: "phr.", meaning: "确保，确认", category: "phrase", example: "Make sure you lock the door before leaving.", tip: "常接that从句，也可以接of短语" },
    { word: "no longer", pos: "phr.", meaning: "不再", category: "phrase", example: "He no longer lives here.", tip: "等于not...any longer，放在行为动词前，be动词/助动词后" },
    { word: "set up", pos: "phr.", meaning: "建立，设立", category: "phrase", example: "They set up a new school in the area.", tip: "set-set-set，指创建、设立机构或帐篷等" },
    { word: "stay up", pos: "phr.", meaning: "熬夜", category: "phrase", example: "Don't stay up too late.", tip: "stay up late/doing sth.，不及物短语" },
    { word: "take care of", pos: "phr.", meaning: "照顾，处理", category: "phrase", example: "She takes care of her grandmother.", tip: "同义短语是look after，其名词形式可以受形容词修饰，如 take good care of" },
    { word: "take part in", pos: "phr.", meaning: "参加", category: "phrase", example: "He took part in the sports meeting.", tip: "join指加入组织、政党、人群；take part in指参加群众性的活动、比赛、会议" },
    { word: "turn off", pos: "phr.", meaning: "关闭（开关、水源、电器）", category: "phrase", example: "Please turn off the lights before leaving.", tip: "反义是turn on，如果是代词作宾语必须放中间：turn it/them off" },
    { word: "worry about", pos: "phr.", meaning: "担心，焦虑", category: "phrase", example: "Don't worry about the exam.", tip: "形容词短语是be worried about" },
    // --- 新增上海中考高频短语 ---
    { word: "prevent ... from", pos: "phr.", meaning: "阻止/防止...做某事", category: "phrase", example: "The heavy rain prevented us from going out.", tip: "prevent sb. from doing sth.，其中from可省略，但在被动语态中不可省" },
    { word: "can't help doing", pos: "phr.", meaning: "情不自禁地做某事", category: "phrase", example: "I couldn't help laughing when I heard the joke.", tip: "上海中考常考非谓语动词结构，help后面接doing，意为'忍不住'" },
    { word: "in a hurry", pos: "phr.", meaning: "急忙地，匆忙地", category: "phrase", example: "She left the room in a hurry.", tip: "介词短语，在句中作状语。 hurry也是动词：hurry up (快点)" },
    { word: "make up one's mind", pos: "phr.", meaning: "下定决心，决定", category: "phrase", example: "He made up his mind to study abroad.", tip: "等同于decide/make a decision，后面跟 to do sth." },
    { word: "hear from", pos: "phr.", meaning: "收到某人的来信", category: "phrase", example: "I look forward to hearing from you soon.", tip: "后面加表示人的名词或代词，相当于receive a letter from sb." }
];

// 专为词性转换 (Zhongkao Section B: Word Form Completion) 设计的特色考题库
const TRANSFORMATION_DB = [
    { original: "beauty", target: "beautiful", direction: "名词 变为 形容词", explanation: "-ty 结尾的抽象名词变成形容词通常变 y 为 i 加 -ful。" },
    { original: "clear", target: "clearly", direction: "形容词 变为 副词", explanation: "直接在词尾加 -ly 变成副词。" },
    { original: "danger", target: "dangerous", direction: "名词 变为 形容词", explanation: "名词 danger 加后缀 -ous 变成形容词。" },
    { original: "health", target: "healthy", direction: "名词 变为 形容词", explanation: "名词 health 直接加 -y 变为形容词。" },
    { original: "honest", target: "honesty", direction: "形容词 变为 名词", explanation: "形容词词尾加 -y 变成抽象名词。" },
    { original: "invent", target: "inventor", direction: "动词 变为 表示\"人\"的名词", explanation: "invent (发明) + -or = inventor (发明家)。注意不是-er。" },
    { original: "noise", target: "noisy", direction: "名词 变为 形容词", explanation: "去 e 加 y 变成形容词 noisy。" },
    { original: "possible", target: "possibly", direction: "形容词 变为 副词", explanation: "以 -le 结尾的形容词，去 e 加 y 变成副词。" },
    { original: "sad", target: "sadness", direction: "形容词 变为 名词", explanation: "形容词 + -ness 变成表示情感的抽象名词。" },
    { original: "succeed", target: "successful", direction: "动词 变为 形容词", explanation: "名词是 success，形容词是 successful，注意双写c和s。" },
    { original: "friend", target: "friendly", direction: "名词 变为 形容词", explanation: "名词 friend + -ly 变为形容词，意为\"友好的\"，注意该词为形容词而非副词。" },
    { original: "differ", target: "difference", direction: "动词 变为 名词", explanation: "动词 + -ence 结尾变成名词形式，形容词是different。" },
    { original: "ill", target: "illness", direction: "形容词 变为 名词", explanation: "形容词 + -ness 构成名词，指\"疾病\"。" },
    { original: "introduce", target: "introduction", direction: "动词 变为 名词", explanation: "以 -uce 结尾的动词，去 e 变 uction 表示名词。" },
    { original: "meaning", target: "meaningful", direction: "名词 变为 形容词", explanation: "名词 meaning + -ful 构成形容词，\"有意义的\"。反义词是meaningless。" },
    { original: "act", target: "action", direction: "动词 变为 名词", explanation: "动词 act + -ion 变成名词 action（行动/活动）。" },
    { original: "busy", target: "business", direction: "形容词 变为 名词", explanation: "busy 变 y 为 i 加 -ness 变成名词，注意拼写中i的存在，意为\"生意，商业\"。" },
    { original: "collect", target: "collection", direction: "动词 变为 名词", explanation: "动词 collect + -ion 变成名词 collection（收藏品/收集）。" },
    { original: "educate", target: "education", direction: "动词 变为 名词", explanation: "动词 educate 去 e + -ion 变成名词 education（教育）。" },
    { original: "express", target: "expression", direction: "动词 变为 名词", explanation: "动词 express + -ion 变成名词 expression（表达/表情）。" },
    { original: "fortune", target: "fortunate", direction: "名词 变为 形容词", explanation: "名词 fortune(财富/运气) 去 e + -ate 变成形容词 fortunate（幸运的，相当于lucky）。" },
    { original: "happy", target: "happiness", direction: "形容词 变为 名词", explanation: "happy 变 y 为 i 加 -ness 变成名词 happiness（幸福，快乐）。" },
    { original: "imagine", target: "imagination", direction: "动词 变为 名词", explanation: "动词 imagine 去 e + -ation 变成名词 imagination（想象力）。" },
    { original: "polite", target: "politely", direction: "形容词 变为 副词", explanation: "以 -te 结尾的形容词直接加 -ly 变成副词，注意保留e。" },
    { original: "safe", target: "safety", direction: "形容词 变为 名词", explanation: "形容词 safe 去 e + -ty 变成名词 safety（安全），注意拼写。" },
    { original: "serious", target: "seriously", direction: "形容词 变为 副词", explanation: "以 -ous 结尾的形容词直接加 -ly 变成副词。" },
    { original: "tradition", target: "traditional", direction: "名词 变为 形容词", explanation: "名词 tradition + -al 变成形容词 traditional（传统的）。" },
    { original: "value", target: "valuable", direction: "名词 变为 形容词", explanation: "名词 value 去 e + -able 变成形容词 valuable（有价值的）。" },
    { original: "wonder", target: "wonderful", direction: "动词 变为 形容词", explanation: "动词/名词 wonder + -ful 变成形容词 wonderful（精彩的）。" },
    { original: "science", target: "scientist", direction: "名词 变为 表示\"人\"的名词", explanation: "名词 science 变 ce 为 t + -ist 变成 scientist（科学家）。" },
    
    // --- 新增上海中考超高频词性转换考点 ---
    { original: "die", target: "death", direction: "动词 变为 名词", explanation: "上海中考最经典考点：die(动词) -> death(名词)；形容词是dead(已死的)，现在分词是dying(垂死的)。" },
    { original: "choose", target: "choice", direction: "动词 变为 名词", explanation: "经典不规则变化：动词choose -> 名词choice。例如：make a choice。" },
    { original: "high", target: "height", direction: "形容词 变为 名词", explanation: "极高频考点：形容词high(高的) -> 名词height(高度/身高)，注意拼写中含有e-i-g-h-t。" },
    { original: "strong", target: "strength", direction: "形容词 变为 名词", explanation: "极高频考点：形容词strong(强壮的) -> 名词strength(力量，长处)，注意中间元音字母变化且尾部加gth。" },
    { original: "true", target: "truth", direction: "形容词 变为 名词", explanation: "形容词true(真实的) -> 名词truth(真理/事实)。副词是truly(去e加ly)。" },
    { original: "hot", target: "heat", direction: "形容词 变为 名词/动词", explanation: "形容词hot(热的) -> 名词/动词heat(热度，加热)。" },
    { original: "please", target: "pleasant", direction: "动词 变为 形容词(修饰物)", explanation: "please(使高兴) -> pleasant(令人愉快的，常修饰物)。如果是人感到高兴，用pleased。" },
    { original: "anger", target: "angry", direction: "名词 变为 形容词", explanation: "名词anger(愤怒) -> 形容词angry(生气的)，副词是angrily(变y为i加ly)。" },
    { original: "heavy", target: "heavily", direction: "形容词 变为 副词", explanation: "上海中考常考：heavy -> heavily (下大雨/雪 rainy/snowy heavily)。变y为i加ly。" },
    { original: "bad", target: "badly", direction: "形容词 变为 副词", explanation: "bad(坏的) -> badly(恶劣地/严重地)。注意：其比较级和最高级是不规则的(worse, worst)。" },
    { original: "dry", target: "drier", direction: "形容词 变为 比较级", explanation: "dry(干燥的) -> drier(更干燥的)，变y为i加er。最高级是driest。" },
    { original: "freeze", target: "frozen", direction: "动词 变为 形容词", explanation: "动词freeze(结冰)的过去分词作形容词：frozen(冰冻的)。" },
    { original: "shame", target: "shameful", direction: "名词 变为 形容词", explanation: "shame(羞耻/遗憾) -> shameful(可耻的)；也可构成形容词shameless(无耻的)。" },
    { original: "care", target: "careless", direction: "名词/动词 变为 否定形容词", explanation: "上海中考必考：care -> careless(粗心的)，反义词是careful(细心的)，名词是carelessness。" },
    { original: "harm", target: "harmful", direction: "名词/动词 变为 形容词", explanation: "harm -> harmful(有害的)，be harmful to sb. 对某人有害。反义词是harmless(无害的)。" },
    { original: "wealth", target: "wealthy", direction: "名词 变为 形容词", explanation: "名词wealth(财富) -> 形容词wealthy(富裕的，相当于rich)。" },
    { word: "tour", target: "tourist", direction: "名词 变为 表示\"人\"的名词", explanation: "tour(旅游) + -ist = tourist(游客，观光客)。" },
    { original: "hero", target: "heroes", direction: "名词 单数变为复数", explanation: "上海中考最爱考：以o结尾的名词复数加-es的词：heroes(英雄), tomatoes(西红柿), potatoes(土豆)。" },
    { original: "thief", target: "thieves", direction: "名词 单数变为复数", explanation: "以f/fe结尾的名词变复数，变f为v加-es：thief -> thieves，knife -> knives，life -> lives。" },
    
    // --- 上海中考首尾句/句型转换核心：基数词变序数词 ---
    { original: "one", target: "first", direction: "基数词 变为 序数词", explanation: "一(one) 变为 第一(first)，缩写为 1st。" },
    { original: "two", target: "second", direction: "基数词 变为 序数词", explanation: "二(two) 变为 第二(second)，缩写为 2nd。" },
    { original: "three", target: "third", direction: "基数词 变为 序数词", explanation: "三(three) 变为 第三(third)，缩写为 3rd。" },
    { original: "five", target: "fifth", direction: "基数词 变为 序数词", explanation: "上海中考经典：五(five) 变 ve 为 f 加 th 变成 第五(fifth)。" },
    { original: "eight", target: "eighth", direction: "基数词 变为 序数词", explanation: "八(eight) 变 第八(eighth)，注意末尾只有一个t。" },
    { original: "nine", target: "ninth", direction: "基数词 变为 序数词", explanation: "九(nine) 去 e 加 th 变成 第九(ninth)，千万不要写成nineth。" },
    { original: "twelve", target: "twelfth", direction: "基数词 变为 序数词", explanation: "上海中考最易错：十二(twelve) 变 ve 为 f 加 th 变成 第十二(twelfth)。" },
    { original: "twenty", target: "twentieth", direction: "基数词 变为 序数词", explanation: "整十位数变序数词：把 y 变 ie 再加 th。二十(twenty) -> 第二十(twentieth)。" }
];

const CATEGORY_MAP = {
    all: "全部词汇",
    noun: "核心名词",
    verb: "核心动词",
    adj_adv: "形容词与副词",
    phrase: "高频短语"
};